IF(UNIX)
	FIND_PROGRAM(GCC_CONFIG_EXECUTABLE gcc-config)
	MARK_AS_ADVANCED(GCC_CONFIG_EXECUTABLE)
	IF(GCC_CONFIG_EXECUTABLE)
		EXECUTE_PROCESS(COMMAND ${GCC_CONFIG_EXECUTABLE} -L
			OUTPUT_VARIABLE GCC_CONFIG_OUTPUT
			RESULT_VARIABLE GCC_CONFIG_RESULT)
		IF(NOT GCC_CONFIG_RESULT)
			STRING(REGEX REPLACE "\n" "" GCC_CONFIG_OUTPUT "${GCC_CONFIG_OUTPUT}")
			STRING(REPLACE ":" ";" GCC_CONFIG_OUTPUT "${GCC_CONFIG_OUTPUT}")
			SET(CC_LIBRARIES ${GCC_CONFIG_OUTPUT})
		ENDIF(NOT GCC_CONFIG_RESULT)
	ENDIF(GCC_CONFIG_EXECUTABLE)

	SET(CC_INCLUDE_PATH)
	FOREACH(LIB ${CC_LIBRARIES})
		SET(CC_INCLUDE_PATH ${CC_INCLUDE_PATH} "${LIB}/include")
	ENDFOREACH(LIB)
	MESSAGE("CC_INCLUDE_PATH=${CC_INCLUDE_PATH}")
	MESSAGE("CC_LIBRARIES=${CC_LIBRARIES}")
ENDIF(UNIX)


INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CCLibs DEFAULT_MSG CC_LIBRARIES CC_INCLUDE_PATH)
